SET FOREIGN_KEY_CHECKS = 0;
USE `fredi21`;

DROP TABLE IF EXISTS `ligue`;

CREATE TABLE `ligue` (
  `id_ligue` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `lib_ligue` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1;